/**
 * Swagger sample app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Releve {
    /**
     * id
     */
    id?: number;
    /**
     * plantId
     */
    plantId?: number;
    /**
     * userId
     */
    userId?: number;
    /**
     * indexCompteur
     */
    indexCompteur?: number;
    /**
     * timestamp
     */
    timestamp?: Date;
}
